# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steady', '0004_auto_20160325_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
